### ISSUE TITLE
Write high level requirements

### ISSUE THREAD

**Issue by lillalysmasken3** [JesperMell/Continuous_integration_3557h#4]
The high level requirements for this project must be set before we can proceed with the lower level requirements, and implementation of this.

**Comment by lillalysmasken3** [comment]
![722A62BF-A373-4C12-AEFD-7D14AD34BBD6](https://user-images.githubusercontent.com/11899679/76075998-45476600-5f9e-11ea-94ac-215767b49e4a.jpeg)

**Comment by lillalysmasken3** [comment]
according to the image the flow for actions should be as follows.

Once the code is changed, unity tests should be run and passed.
The code should be pushed to github on that specific feature branch.
When the code is pushed, the makefile should compile the code with all its dependencies.
The program should then be tested by some python tests.

After successful testing, the code can be merged into  ̷m̷a̷i̷n̷   Development branch, and the feature branch should be deleted.
_idea: run additional tests on merge?_

When all features are ready for initial release, merge the code into main.
_idea: run additional tests on merge?_
on merge to main, a release should be automaticly built. it should include:
- the source code in a .zip file.
- The excecutable.
- some instructions.
- a config file
- A label (e.g V1.0)

**Comment by lillalysmasken3** [comment]
@dark3ad  Jag lade till dig som assignee för detta.
Det finns under "high_level_requirement" branchen en mapp som heter documents.
i den finns det högnivåkrav.
Än så länge är det mer eller mindre ett skelett men jag tänker att du o jag kan jobba på detta.
jag har försökt samla lite ideér o tankar jag har i denna tråden.

**Comment by dark3ad** [comment]
Låter bra. Vi går igenom det på tisdag skarpt


Med vänlig hälsning,
Best regards

Patrik Gustafsson


Informationen i detta meddelande kan vara konfidentiellt och är endast avsedd för mottagaren. Om du inte är den tänkta mottagaren av denna information ber vi dig meddela avsändaren och därefter radera meddelandet, tack.

The information contained in this message may be CONFIDENTIAL and is intended for the addressee only. Any unauthorized use, dissemination of the information or copying of this message is prohibited. If you are not the addressee, please notify the sender immediately by returning this e-mail and deleting the message. Thank you.

________________________________

**Comment by lillalysmasken3** [comment]
Vi har uppdaterat högnivåkraven med feedback från Joachim.
Vi har även skapat en standard för vårt arbetsflöde.

**Comment by lillalysmasken3** [comment]
High level requrements merged
